services:
  private-gpt:
    build:
      dockerfile: Dockerfile.external
    networks:
      - private-gpt_internal-network
      - my-app-network
    volumes:
      - ./local_data/:/home/worker/app/local_data
    ports:
      - 8001:8080
    environment:
      PORT: 8080
      PGPT_PROFILES: docker
      PGPT_MODE: ollama
  ollama:
    image: ollama/ollama:latest
    networks:
      - private-gpt_internal-network
    volumes:
      - ./models:/root/.ollama
networks:
  private-gpt_internal-network:
    driver: bridge
  my-app-network:
    external: true